- block:
    - name: Create OVN key temporary files
      ansible.builtin.tempfile:
        state: file
        suffix: ovn
      register: ovnkey

    - name: Generate OVN CSR
      ansible.builtin.command: |
        '/usr/bin/openssl'
        'req'
        '-new'
        '-newkey'
        '{{ ovirt_ovn_key_type }}:{{ ovirt_ovn_key_size }}'
        '-nodes'
        '-subj'
        '/'
        '-keyout'
        '{{ ovnkey.path }}'
      register: csr

    - name: Copy OVN CSR
      ansible.builtin.copy: # noqa template-instead-of-copy
        content: "{{ csr.stdout }}"
        dest: "{{ ovirt_pki_dir }}/requests/{{ ovirt_vds_hostname }}-ovn.req"
        mode: 0644
      delegate_to: localhost

    - name: Run PKI enroll request for OVN
      ansible.builtin.command: |
        "{{ ovirt_engine_usr }}/bin/pki-enroll-request.sh"
        "--name={{ ovirt_vds_hostname }}-ovn"
        "--subject=/O={{ ovirt_organizationname }}/CN={{ ovirt_vds_hostname }}"
        "--san={{ ovirt_san }}"
        "--days={{ ovirt_vds_certificate_validity_in_days }}"
        "--timeout={{ ovirt_signcerttimeoutinseconds }}"
      delegate_to: localhost

    - name: Prepare directory for OVN certificate files
      ansible.builtin.file:
        dest: "{{ ovirt_vdsm_trust_store ~ '/' ~ ovirt_ovn_cert_file | dirname }}"
        state: directory
        owner: 'openvswitch'
        group: 'openvswitch'
        mode: 0755

    - name: Add OVN cacert file
      ansible.builtin.copy: # noqa template-instead-of-copy
        content: "{{ ovirt_ca_cert }}"
        dest: "{{ ovirt_vdsm_trust_store }}/{{ ovirt_ovn_ca_file }}"
        owner: 'openvswitch'
        group: 'openvswitch'
        mode: 0644

    - name: Add OVN cert file
      ansible.builtin.copy:
        src: "{{ ovirt_pki_dir }}/certs/{{ ovirt_vds_hostname }}-ovn.cer"
        dest: "{{ ovirt_vdsm_trust_store }}/{{ ovirt_ovn_cert_file }}"
        owner: 'openvswitch'
        group: 'openvswitch'
        remote_src: false
        mode: preserve

    - name: Add OVN key file
      ansible.builtin.copy:
        src: "{{ ovnkey.path }}"
        dest: "{{ ovirt_vdsm_trust_store }}/{{ ovirt_ovn_key_file }}"
        owner: 'openvswitch'
        group: 'openvswitch'
        mode: 0440
        remote_src: true

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Restart OVN services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - openvswitch.service
        - openvswitch-ipsec.service
        - ovn-controller.service
      when: "ansible_facts.services.get(item, {}).get('status') == 'enabled'"

  always:
    - name: Remove temp file
      ansible.builtin.file:
        state: absent
        path: "{{ ovnkey.path }}"
