---
- block:
    - name: Install ovs
      ansible.builtin.package:
        name: openvswitch
        state: present

    - name: Ensure Open vSwitch is started
      ansible.builtin.service:
        name: openvswitch
        state: started
        enabled: true

  when:
    - cluster_switch == "ovs" or (ovn_central is defined)

- block:
    - name: Install ovirt-provider-ovn-driver
      ansible.builtin.package:
        name: ovirt-provider-ovn-driver
        state: present

    - name: Ensure ovn-controller is started
      ansible.builtin.service:
        name: ovn-controller
        state: started
        enabled: true

    - name: Fetch installed packages
      ansible.builtin.package_facts:
        manager: rpm

    - name: Get installed version of vdsm
      ansible.builtin.set_fact:
        vdsm_package: "{{ ansible_facts.packages['vdsm'] | first }}"

    - name: Skip Host FQDN for vdsm older than 4.50
      ansible.builtin.set_fact:
        ovn_host_fqdn: ""
      when:
        - vdsm_package.version is version('4.50', '<')

    - name: Configure OVN for oVirt
      ansible.builtin.command: >
          vdsm-tool ovn-config {{ ovn_central }} {{ ovn_tunneling_interface }} {{ ovn_host_fqdn }}

  when:
    - ovn_central is defined
